import Foundation

// Unit M-store-screens (round3-deferred), seed catalog lane. Owner report
// from the real iPhone, 2026-09-28: "There are no mobile apps to browse."
// publikhq.com answers 404 for the mobile catalog v2 and the v1 list only
// has Mac apps, so Browse was empty on every phone.
//
// The fix is a catalog of last resort that ships inside the app: the three
// apps that already come with Iris (Kneecap, Nut AI, FreeHarmony), as the
// exact catalog v2 files publikhq.com would serve (`StoreCatalogSeedData`,
// generated by mobile-shell/website/seed-catalog-v2.mjs, which also writes
// the website copy). Order of preference, decided in `StoreCatalogFeed`:
// the network index, then the on-disk cache, then this seed.
//
// The seed is decoded through a real `PublikMobileCatalogClient` whose
// transport answers only the seed's own URLs, so it passes the same
// parser, field checks, byte caps, MIME check and icon hash check as a
// network answer. A seed that fails any of them is not used at all
// (`bundled()` returns nil), never half-used.

public struct StoreCatalogSeed: Sendable {
    public let snapshot: PublikMobileCatalogV2Snapshot
    public let categories: [PublikMobileCatalogCategoryV2]
    /// Each app's page (description, permissions, install descriptor).
    public let pages: [String: PublikMobileCatalogAppPageV2]
    /// Icon bytes by `iconHash`, already checked against that hash.
    public let icons: [String: Data]

    /// The quiet line under Browse while only the seed is on screen.
    public static let statusLine = "Showing the apps that came with Iris. More apps appear when publikhq.com lists them."
    /// Same, while the first check is still running.
    public static let checkingLine = "Checking for new apps. Showing the apps that came with Iris."
    /// Under the disabled button for a listed app that Iris has no files for
    /// and no hosted package to download, so Get cannot install it. It says
    /// why, plainly (round6/catalog-expand, SPEC.md acceptance 7). It never asks
    /// the person to close Iris and never shows a failed download.
    public static let notInstalledNote = "Publik has not published this app for iPhone yet. Check back later."

    /// What a seed row's button offers. The seed's download addresses may
    /// not exist yet, so it never offers a download: Iris itself installs
    /// and updates the starters every time it starts.
    /// - Installed at the listed revision: the normal listing, so Open.
    /// - Installed at an older revision: still Open (not a failing Update).
    /// - Not installed and no files inside Iris to set it up from: a disabled
    ///   button with a plain reason (`notInstalledNote`), no Get.
    ///
    /// RC-11: when Iris still carries the app's starter files inside itself
    /// (`canReinstallFromBundle`), an app that is not on this phone offers a
    /// real Get, which sets it up again from those files (`StoreSeedReinstall`)
    /// instead of asking the person to close and reopen Iris.
    public static func listing(
        for descriptor: PublikMobileShellDescriptor,
        installedRevisionId: String?,
        canReinstallFromBundle: Bool = false
    ) -> StoreInstallFacts.Listing {
        if installedRevisionId == descriptor.revisionId
            || (installedRevisionId == nil && canReinstallFromBundle) {
            return .listed(revisionId: descriptor.revisionId, baseRevisionId: descriptor.baseRevisionId)
        }
        return .unavailable(reason: notInstalledNote)
    }

    /// Every app the seed lists, in catalog order.
    public var apps: [PublikMobileCatalogIndexAppV2] { snapshot.apps }

    /// What Browse paints from the seed: the rows, the categories, and each
    /// row's install descriptor (so an installed starter shows Open without
    /// opening its page first).
    public var load: StoreCatalogLoad {
        StoreCatalogLoad(
            snapshot: snapshot,
            legacyRows: nil,
            categories: categories,
            seedDescriptors: pages.mapValues(\.mobileShell)
        )
    }

    // MARK: decoding

    enum SeedError: Error, Equatable {
        case damagedFile(String)
        case moreThanOnePage
        case disagreesWithPage(String)
    }

    /// Decodes a seed from catalog files keyed by their path under
    /// `catalogRoot` ("index.json", "categories.json", "apps/<slug>.json",
    /// "icons/<hash>.png"). Throws on the first problem.
    static func decode(files: [String: Data], catalogRoot: String = StoreCatalogSeedData.catalogRoot) async throws -> StoreCatalogSeed {
        var byURL: [String: Data] = [:]
        for (path, body) in files { byURL[catalogRoot + path] = body }
        let client = PublikMobileCatalogClient(transport: StoreCatalogSeedTransport(files: byURL))

        let first = try await client.fetchIndexPage(1, cache: nil).value
        guard first.pageCount == 1 else { throw SeedError.moreThanOnePage }
        let categories = try await client.fetchCategories(cache: nil).value.categories
        var pages: [String: PublikMobileCatalogAppPageV2] = [:]
        var icons: [String: Data] = [:]
        for app in first.apps {
            let page = try await client.fetchAppPage(slug: app.slug, cache: nil).value
            // The two facts a person acts on before tapping must agree
            // between the row and the page (contract rule), and the row's
            // optional latest revision must name the page's revision.
            guard page.mobileShell.byteCount == app.byteCount,
                  app.latestRevisionId == nil || app.latestRevisionId == page.mobileShell.revisionId else {
                throw SeedError.disagreesWithPage(app.slug)
            }
            pages[app.slug] = page
            icons[app.iconHash] = try await client.fetchIcon(for: app)
        }
        let snapshot = PublikMobileCatalogV2Snapshot(
            generatedAt: first.generatedAt,
            pageCount: first.pageCount,
            pages: [first],
            lastCheckedAt: .distantPast,
            isStale: false
        )
        return StoreCatalogSeed(snapshot: snapshot, categories: categories, pages: pages, icons: icons)
    }

    /// The generated files, each checked against its recorded sha256.
    static func bundledFiles() throws -> [String: Data] {
        var files: [String: Data] = [:]
        for file in StoreCatalogSeedData.files {
            guard let bytes = Data(base64Encoded: file.base64), NativeSecurity.sha256(bytes) == file.sha256 else {
                throw SeedError.damagedFile(file.path)
            }
            files[file.path] = bytes
        }
        return files
    }

    /// The seed that ships inside Iris, decoded once per launch. Nil only if
    /// the shipped files are damaged, which a test guards against.
    public static func bundled() async -> StoreCatalogSeed? {
        await StoreCatalogSeedCache.shared.bundled()
    }
}

private actor StoreCatalogSeedCache {
    static let shared = StoreCatalogSeedCache()
    private var decoded: StoreCatalogSeed??

    func bundled() async -> StoreCatalogSeed? {
        if let decoded { return decoded }
        let seed = try? await StoreCatalogSeed.decode(files: StoreCatalogSeed.bundledFiles())
        decoded = .some(seed)
        return seed
    }
}

/// Answers GETs for the seed's own URLs from memory, like a server that has
/// exactly these files. Every other URL is a 404.
struct StoreCatalogSeedTransport: PublikMobileHTTPTransport {
    let files: [String: Data]

    func get(_ request: URLRequest, maximumBytes: Int, progress: (@Sendable (Int) -> Void)?) async throws -> PublikMobileHTTPResponse {
        guard let url = request.url, let body = files[url.absoluteString] else {
            throw PublikMobileDownloadError.unexpectedStatus(404)
        }
        return PublikMobileHTTPResponse(
            statusCode: 200,
            mimeType: url.pathExtension == "png" ? "image/png" : "application/json",
            declaredContentLength: body.count,
            finalURL: url,
            body: body
        )
    }
}

// MARK: - The feed's use of the seed (hooks in StoreCatalogFeed.swift)

extension StoreCatalogFeed {
    /// The feed Browse uses in the app: network, then disk, then the seed
    /// that ships inside Iris. `StoreModel` and the persona simulator both
    /// build it here, so they cannot drift apart.
    public static func withBundledSeed(client: PublikMobileCatalogClient, cache: PublikMobileCatalogCache?, now: @escaping @Sendable () -> Date = { Date() }) -> StoreCatalogFeed {
        StoreCatalogFeed(client: client, cache: cache, now: now, seed: { await StoreCatalogSeed.bundled() })
    }

    /// The seed as a load, with its app pages kept in memory so an app page
    /// opens without a request that is known to fail.
    func seedLoad() async -> StoreCatalogLoad? {
        guard let seedSource, let seed = await seedSource() else { return nil }
        for (slug, page) in seed.pages where pages[slug] == nil {
            pages[slug] = page
            seededPageSlugs.insert(slug)
        }
        return seed.load
    }

    /// A real catalog replaced the seed: forget the seed's pages so a page
    /// opened from the real catalog is fetched, never answered by the seed.
    func forgetSeedPages() {
        for slug in seededPageSlugs { pages[slug] = nil }
        seededPageSlugs.removeAll()
    }

    /// Publik answered with the v1 list (index v2 is 404). Rows that no
    /// iPhone can install (the Mac list, today) leave Browse empty, so the
    /// seed stands in until Publik lists mobile apps.
    func legacyOrSeed(_ rows: [PublikMobileCatalogApp]) async -> StoreCatalogLoad {
        if !rows.contains(where: NativeMobileMarketplacePolicy.isVisibleInBrowse), let seed = await seedLoad() {
            return seed
        }
        forgetSeedPages()
        return StoreCatalogLoad(snapshot: nil, legacyRows: rows, categories: [])
    }

    /// The seed's page for `slug`, while the seed is what Browse shows.
    func seedPage(_ slug: String) -> PublikMobileCatalogAppPageV2? {
        seededPageSlugs.contains(slug) ? pages[slug] : nil
    }
}

extension StoreApp {
    /// The same row with an install descriptor attached (seed rows only).
    func withDescriptor(_ descriptor: PublikMobileShellDescriptor?) -> StoreApp {
        StoreApp(
            slug: slug, name: name, summary: summary, categoryIds: categoryIds,
            iconHash: iconHash, iconURL: iconURL, byteCount: byteCount, ageRating: ageRating,
            updatedAt: updatedAt, badges: badges, isFeatured: isFeatured, isSponsored: isSponsored,
            placementLabel: placementLabel, catalogOrder: catalogOrder, descriptor: descriptor,
            latestRevisionId: latestRevisionId,
            publisher: publisher
        )
    }
}
