#if os(iOS)
import CryptoKit
import Foundation
import UIKit
import XCTest
@testable import IrisMobileShellCore
@testable import IrisMobileShellHost

/// Round 3 (long-clip import, 2026-09-28): provider transfer, borrowed-input copying, the
/// launch-time stale-lease sweep, and multi-clip batch rollback. Companion
/// to NativeMediaLeaseSafetyTests.swift; split into its own file because all
/// of this is new behavior this round added, not the pre-existing safety
/// net that file already covers.
///
/// Oracles here are independent of the code's own opinion of itself: a
/// SHA-256 of the real bytes on disk (not a re-read the code itself could
/// have gotten wrong the same way twice), and real `FileManager` existence
/// checks (not a return value the code hands back about itself).
@MainActor
final class NativeMediaImportMoveAndCleanupTests: XCTestCase {

    // MARK: Provider transfer and borrowed input preservation (G7)

    func testALocalPickerFileIsMovedNotCopiedIntoTheLeaseAndBytesHashMatchTheSource() throws {
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }
        let bytes = Data((0..<200_000).map { UInt8($0 % 251) })
        let source = fixture.file(named: "provider-clip.mov", bytes: bytes)
        let expectedHash = SHA256.hash(data: bytes)

        let lease = try NativeSelectedMediaLease(parent: fixture.root)
        defer { lease.close() }
        let batch = try lease.beginBatch()
        let selected: URL
        do {
            selected = try lease.copySelectedFile(source, fileExtension: "mov", kind: .video,
                                                 batch: batch, takingProviderTemporaryFile: true)
            try lease.commit(batch)
        } catch {
            lease.rollback(batch)
            throw error
        }

        // Mutation N3: copying a same-volume provider temporary file leaves its source and fails.
        XCTAssertFalse(FileManager.default.fileExists(atPath: source.path),
                       "a same-volume move must not leave the picker's source file behind")
        XCTAssertNotEqual(selected.standardizedFileURL, source.standardizedFileURL)
        XCTAssertEqual(SHA256.hash(data: try Data(contentsOf: selected)), expectedHash,
                       "provider transfer must preserve independently generated source bytes")
        lease.close()
        XCTAssertFalse(FileManager.default.fileExists(atPath: selected.path), "closing releases the transferred file")
    }

    func testExplicitBorrowedPickerFilePreservesCallerBytesAndLeaseCloseRemovesOnlyTheCopy() throws {
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }
        let bytes = Data((0..<200_000).map { UInt8($0 % 251) }) // real varied bytes, not all-zero
        let source = fixture.file(named: "clip.mov", bytes: bytes)
        let expectedHash = SHA256.hash(data: bytes)

        let lease = try NativeSelectedMediaLease(parent: fixture.root)
        defer { lease.close() }
        let batch = try lease.beginBatch()
        let copied: URL
        do {
            copied = try lease.copySelectedFile(source, fileExtension: "mov", kind: .video,
                                               batch: batch, takingProviderTemporaryFile: false)
            try lease.commit(batch)
        } catch {
            lease.rollback(batch)
            throw error
        }

        // Mutation N3: moving a caller-owned file fails source existence and its independent hash.
        XCTAssertTrue(FileManager.default.fileExists(atPath: source.path), "copying selected media preserves the caller's file")
        XCTAssertEqual(SHA256.hash(data: try Data(contentsOf: source)), expectedHash)
        XCTAssertNotEqual(copied.standardizedFileURL, source.standardizedFileURL)
        let copiedBytes = try Data(contentsOf: copied)
        XCTAssertEqual(SHA256.hash(data: copiedBytes), expectedHash, "the leased copy exactly matches independently generated bytes")
        lease.close()
        XCTAssertFalse(FileManager.default.fileExists(atPath: copied.path), "closing the lease releases its copy")
        XCTAssertEqual(SHA256.hash(data: try Data(contentsOf: source)), expectedHash, "closing must leave caller data intact")
    }

    func testAttemptAtomicMoveOfANonexistentSourceFailsCleanlyRatherThanCrashingOrPartiallyWriting() {
        // rename(2) across two genuinely different filesystems cannot be
        // reliably forced in this environment (no guaranteed second
        // writable volume in CI), so the "move impossible" branch is proved
        // here at the boundary (a rename that must fail) plus, in the test
        // above, by the fact that a mutation forcing `attemptAtomicMove` to
        // always return false routes every move test through the exact same
        // chunked-copy fallback `copySelectedFile` already exercises for
        // real -- see this task's HANDOFF.md, mutation M-move.
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent("iris-media-move-missing-" + UUID().uuidString)
        let destination = FileManager.default.temporaryDirectory
            .appendingPathComponent("iris-media-move-dest-" + UUID().uuidString)
        XCTAssertFalse(NativeSelectedMediaLease.attemptAtomicMove(from: missing, to: destination))
        XCTAssertFalse(FileManager.default.fileExists(atPath: destination.path))
    }

    func testChunkedCopyFallbackProducesHashIdenticalBytesWhenCalledDirectly() throws {
        // Exercises the exact chunked-copy code path `copySelectedFile` falls
        // back to whenever a move is not possible, by using a source/
        // destination pair one directory apart from the lease (still the
        // same volume in this environment, so this alone does not prove the
        // "move impossible" branch selection -- see the test above for that
        // half); what it proves is that the fallback's own bytes are correct
        // end to end, independent of whether a move happened to run first.
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }
        let bytes = Data((0..<500_000).map { UInt8(($0 * 7) % 251) })
        let expectedHash = SHA256.hash(data: bytes)
        let source = fixture.file(named: "fallback-source.mov", bytes: bytes)

        let lease = try NativeSelectedMediaLease(parent: fixture.root)
        defer { lease.close() }
        let copied = try lease.copySelectedFile(source, fileExtension: "mov", kind: .video)
        let copiedBytes = try Data(contentsOf: copied)
        XCTAssertEqual(SHA256.hash(data: copiedBytes), expectedHash)
    }

    // MARK: Launch-time stale-lease sweep (app killed mid-import, then relaunched)

    func testSweepStaleLeasesRemovesAKilledSessionsLeaseWithoutFirstCreatingALiveLeaseInThisProcess() throws {
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }

        // Simulate a process that was killed mid-import: a lease directory
        // that got as far as its exact marker and a real file (standing in
        // for a long clip's payload), but never finished -- no lock file,
        // exactly what a crash leaves, since the lock file is the last thing
        // `prepareLeaseDirectory` creates for a real lease.
        let root = fixture.root.appendingPathComponent(NativeSelectedMediaLease.mediaRootName, isDirectory: true)
        try FileManager.default.createDirectory(
            at: root, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700]
        )
        try NativeSelectedMediaLease.rootMarkerData.write(
            to: root.appendingPathComponent(NativeSelectedMediaLease.rootMarkerName), options: .withoutOverwriting
        )
        let killedLease = root.appendingPathComponent(
            NativeSelectedMediaLease.leaseDirectoryPrefix + UUID().uuidString, isDirectory: true
        )
        try FileManager.default.createDirectory(
            at: killedLease, withIntermediateDirectories: false, attributes: [.posixPermissions: 0o700]
        )
        try NativeSelectedMediaLease.leaseMarkerData.write(
            to: killedLease.appendingPathComponent(NativeSelectedMediaLease.leaseMarkerName), options: .withoutOverwriting
        )
        try Data(repeating: 0x4b, count: 8192).write(to: killedLease.appendingPathComponent("clip-in-progress.mov"))
        XCTAssertTrue(FileManager.default.fileExists(atPath: killedLease.path))

        // This is the "app kill, relaunch" oracle: the exact entry point a
        // fresh process's launch path calls, with no lease of its own
        // created in this process first (this task's HANDOFF.md has the one
        // line still to be wired into IrisMobileShellApp.swift).
        try NativeSelectedMediaLease.sweepStaleLeases(parent: fixture.root)

        XCTAssertFalse(
            FileManager.default.fileExists(atPath: killedLease.path),
            "the killed session's lease and its in-progress clip must be swept at launch"
        )
    }

    func testSweepStaleLeasesNeverTouchesALiveLeaseInTheSameProcess() throws {
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }
        let live = try NativeSelectedMediaLease(parent: fixture.root)
        defer { live.close() }
        let liveDirectory = live.directoryForTesting

        try NativeSelectedMediaLease.sweepStaleLeases(parent: fixture.root)

        XCTAssertTrue(FileManager.default.fileExists(atPath: liveDirectory.path), "a live lease must never be reaped by the launch sweep")
    }

    func testPublicLaunchCleanupEntryPointNeverThrowsEvenWhenNothingIsThereToSweep() {
        // The app's own launch path must never fail to launch over this; the
        // narrow public wrapper swallows its error by design (a bad launch
        // sweep must never be the reason the app does not open).
        NativeMediaImportLaunchCleanup.sweepStaleLeases()
    }

    // MARK: Multi-clip batch rollback: no partial N-of-M import

    func testWhenALaterClipInAMultiClipBatchFailsEveryEarlierClipInThatBatchIsRemovedToo() throws {
        let fixture = try MoveCleanupFixture()
        defer { fixture.close() }
        let firstBytes = Data("first clip bytes".utf8)
        let secondBytes = Data("second clip bytes".utf8)
        let first = fixture.file(named: "first.mov", bytes: firstBytes)
        let second = fixture.file(named: "second.mov", bytes: secondBytes)

        let lease = try NativeSelectedMediaLease(parent: fixture.root)
        defer { lease.close() }
        let batch = try lease.beginBatch()
        let firstCopied = try lease.copySelectedFile(first, fileExtension: "mov", kind: .video, batch: batch)
        XCTAssertTrue(FileManager.default.fileExists(atPath: firstCopied.path))
        XCTAssertEqual(lease.retainedFilesForTesting, 1)

        // The second item "fails" (stands in for a provider error, a stall,
        // or a mid-batch rejection): the real picker session's own catch
        // path rolls back the whole batch, not just the failing item (see
        // NativeMediaPickerSession.importResults's catch block).
        lease.rollback(batch)

        XCTAssertFalse(
            FileManager.default.fileExists(atPath: firstCopied.path),
            "an earlier, already-copied clip must not survive a later clip's failure"
        )
        XCTAssertEqual(lease.retainedFilesForTesting, 0)
        XCTAssertEqual(lease.retainedBytesForTesting, 0)
        // Neither original source was touched by the rollback itself.
        XCTAssertEqual(try Data(contentsOf: second), secondBytes)
    }

    func testWaitingIndicatorProgressTextIsAvailableToTheHostAsAPureFunctionMatchingCoresOwnBehavior() {
        // The Host's UIAlertController message is built from this exact Core
        // function (NativeMediaPickerSession.presentWaitingIndicator /
        // refreshWaitingIndicatorProgress); this pins the two stay in sync
        // without needing to drive real UIKit presentation in a unit test.
        XCTAssertEqual(
            NativeMediaImportPolicy.waitingIndicatorMessage(completedItems: 1, totalItems: 3),
            "Long videos can take a minute. Bringing in clip 2 of 3."
        )
    }
}

private final class MoveCleanupFixture {
    let root: URL

    init() throws {
        root = FileManager.default.temporaryDirectory.appendingPathComponent(
            "iris-media-move-cleanup-" + UUID().uuidString, isDirectory: true
        )
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: false)
    }

    func file(named name: String, bytes: Data) -> URL {
        let url = root.appendingPathComponent(name)
        try! bytes.write(to: url)
        return url
    }

    func close() {
        try? FileManager.default.removeItem(at: root)
    }
}
#endif
